### ISSUE TITLE
Not working Ubuntu 20.04

### ISSUE THREAD

**Issue by vpreatoni** [QuasarApp/sdkmanager-android#1]
Your package is not working on Ubuntu 20.04

File gets installed at root location: `/snap/androidsdk/current/tools/bin/sdkmanager`
Path is not exported, so there is no way to just call `$ sdkmanager`

If calling using whole path: `$ /snap/androidsdk/current/tools/bin/sdkmanager --version`
it outputs an error:

```
Warning: Could not create settings
java.lang.IllegalArgumentException
```

**Comment by EndrII** [comment]
Try
**androidsdk [options]**

**androidsdk** it is alias for the snap version of sdkmanager

**Comment by EndrII** [comment]
``` bash 
andrei@X570-GAMING-X:~$ androidsdk 
SDK_ROOT=/home/andrei/snap/androidsdk/24/AndroidSDK
Picked up _JAVA_OPTIONS: -Duser.home=/home/andrei/snap/androidsdk/24
[=======================================] 100% Computing updates...             
andrei@X570-GAMING-X:~$ 

```

using: 
androidsdk --list  // show the installed packages 
androidsdk "platforms;android-29"  // instal android-29 platform

**Comment by EndrII** [comment]
I close this issue due to lack of activity
