### ISSUE TITLE
Command -  sudo snap install androidsdk  giving issue...

### ISSUE THREAD

**Issue by sachinkumaram-veoci** [QuasarApp/sdkmanager-android#6]
**commmand snap androidsdk 1.2.1.1  giving following issue:**

1. Warning: Failed to download any source lists.
2. Warning: IO exception while downloading manifest
3. Warning: Still waiting for package manifests to be fetched remotely.
4.  standard output: Broken pipe
SDK_ROOT=/home/runner/AndroidSDK
Picked up _JAVA_OPTIONS: -Duser.home=/home/runner/snap/androidsdk/61
5. Warning: Failed to find package 'build-tools;33.0.1'

**Comment by EndrII** [comment]
Please show me your command 

I was tried to install this package. All works fine 

```
:~$ androidsdk --install "build-tools;33.0.1"        
SDK_ROOT=/home/andrei/AndroidSDK
Picked up _JAVA_OPTIONS: -Duser.home=/home/andrei/snap/androidsdk/61
[=======================================] 100% Unzipping... android-13/renderscr


```

**Comment by sachinkumaram-veoci** [comment]
> Please show me your command
> 
> I was tried to install this package. All works fine
> 
> ```
> :~$ androidsdk --install "build-tools;33.0.1"        
> SDK_ROOT=/home/andrei/AndroidSDK
> Picked up _JAVA_OPTIONS: -Duser.home=/home/andrei/snap/androidsdk/61
> [=======================================] 100% Unzipping... android-13/renderscr
> ```

It was working fine few days ago with version - **1.2.0.0** , but now with version - **1.2.1.1**  , it creating issue,
I run the following command through GH action : 

 ```
         sudo snap install androidsdk
          yes | androidsdk --licenses
          androidsdk "build-tools;33.0.1" "platforms;android-32"
```

**Comment by EndrII** [comment]
Show me your output log. and your OS version. 

Because i try to execute your commnad "androidsdk "build-tools;33.0.1" "platforms;android-32"" , and this wirks fine for me

**Comment by sachinkumaram-veoci** [comment]
> Show me your output log. and your OS version.
> 
> Because i try to execute your commnad "androidsdk "build-tools;33.0.1" "platforms;android-32"" , and this wirks fine for me

**yml file :-**  
```

 -  runs-on: ubuntu-latest
 - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Yarn 3
        run: |
          corepack enable
          corepack prepare yarn@3.3.0 --activate
          yarn -v

      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v1

      - name: Install Android Build Tools 32
        run: |
          sudo snap install androidsdk
          yes | androidsdk --licenses
          androidsdk "build-tools;33.0.1" "platforms;android-32"


```

**Comment by EndrII** [comment]
i don't know what happened on your device, I checked androidsdk two my devices, and all works fine. 
i can prepare separated channel with old version for you, but you need to solve your issue, because google move build-tools to JDK 17, bat old version contains only JDK11.

```
sudo snap install androidsdk --candidate
```

**Comment by sachinkumaram-veoci** [comment]
> i don't know what happened on your device, I checked androidsdk two my devices, and all works fine. i can prepare separated channel with old version for you, but you need to solve your issue, because google move build-tools to JDK 17, bat old version contains only JDK11.
> 
> ```
> sudo snap install androidsdk --candidate
> ```

Now using : sudo snap install androidsdk --candidate i able to create build through github action..

**Comment by EndrII** [comment]
@sachinkumaram-veoci okay, I will close this issue, but I think should be to create a new branch with old stable releases.
